// Project configuration

projectName: democompany-cards
projectVersion: 0.1.0-SNAPSHOT
subProjects: [
  // subProject1
  // subProject2
]
dependencies: [
  // mastercompany-services
  // mycompany-commons
]
