// year and month you want to release
release.tag = "2025-07"
// a list with existing Releases on the web server
releases.older = []
// flag of this is for the release or just from the TST to see what is going on.
released = true
// this is the url of the release planing, e.g. Jira
jira.release.url = "https://yourReleasePage/versions/64209"
// who is responsible for the Release
release.responsible {
  name = "Peter Blank"
  date = "CHANGE to release date"
}
// what is the release about (abstract as markup)
release.notes = """
- TODO: Describe the Release here
"""
