// Project configuration

projectName: democompany-customer
projectVersion: 0.1.0-SNAPSHOT
subProjects: [
  // subProject1
  // subProject2
]
dependencies: [
  democompany-services
]
// the engine of this project: C7 | C8 | Op - without it the company default (C8)
engineType: Op
