openapi: 3.1.0
info:
  title: democompany-services
  version: 0.1.0-SNAPSHOT
  summary: "\n\nMy services for the democompany\n\nCreated at 08.08.2025, 16:12\n\n\
    **See the [Orchescala Documentation](https://pme123.github.io/orchescala/)**\n\
    \n# Package Configuration\n**Check all dependency trees here: [democompany-services](../../dependencies/democompany-services.html)**\n\
    \n### Dependencies:\n\n\n\n\n<details>\n<summary>PROJECT.conf</summary>\n<p>\n\
    \n```\n\n// Project configuration\n\nprojectName: democompany-services\nprojectVersion:\
    \ 0.1.0-SNAPSHOT\nsubProjects: [\n  // subProject1\n  // subProject2\n]\ndependencies:\
    \ [\n  // mastercompany-services\n  // mycompany-commons\n]\n\n```\n\n</p>\n</details>\n\
    \n\nThere is no README.md in the Project.\n\n\n<details>\n<summary><b><i>CHANGELOG.md</i></b></summary>\n\
    <p>\n\n\nAll notable changes to this project will be documented in this file.\n\
    \n* Types of Changes (L3):\n  * Added: new features\n  * Changed: changes in existing\
    \ functionality\n  * Deprecated: soon-to-be-removed features\n  * Removed: now\
    \ removed features\n  * Fixed: any bug fixes\n  * Security: in case of vulnerabilities\n\
    \n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\n\
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\
    \n\n</p>\n</details>\n\n\n<p/>\n<details>\n<summary>\n<b><i>General Variables</i></b>\n\
    </summary>\n\n<p>\n\n### Mocking\n\n**servicesMocked**:\n\nMock all the _ServiceWorkers_\
    \ in your process with their default Mock:\n\n- DSL:\n```scala\nprocess(..)\n\
    \  .mockServices\n```\n\n- Json\n```json\n...\n\"servicesMocked\": true,\n...\n\
    ```\n\n\n**mockedWorkers**:\n\nMock any Process- and/or ExternalTask-Worker with\
    \ their default Mocks.\nThis is a list of the _Worker topicNames or Process processNames_,\
    \ you want to mock.\nIt is also possible to use a _comma separated_ String,\n\
    like `\"mySubProcess,myOtherSubProcess,myService\"`\n\n_Be aware_: For Sub-Processes,\
    \ this expects an _InitWorker_ where the _topicName_ is equal to the _processName_.\n\
    \n\n- DSL:\n```scala\nprocess(..)\n  .mockedWorkers(\"mySubProcess1\", \"mySubProcess2\"\
    ) // creates a list with SubProcessess\n  .mockedWorker(\"myOtherSubProcess\"\
    ) // adds a SubProcess\n```\n\n- Json\n```json\n...\n\"mockedWorkers\": [\"mySubProcess\"\
    , \"myOtherSubProcess, myService\"],\n...\n```\n\n\n**outputMock**:\n\nMock the\
    \ Process or ExternalTask (`Out`)\n - You find an example in every _Process_ and\
    \ _ExternalTask_.\n\n\n- DSL:\n```scala\nprocess(..) // or serviceTask(..)/customTask(..)\n\
    \  .mockWith(outputMock)\n```\n\n- Json\n```json\n...\n\"outputMock\": {..},\n\
    ...\n```\n\n\n**outputServiceMock**:\n\nMock the Inner-Service (`MockedServiceResponse[ServiceOut]`)\n\
    \ - You find an example in every _ServiceTask_.\n\n\n- DSL:\n```scala\nserviceTask(..)\n\
    \  .mockServiceWith(MockedServiceResponse\n     .success200(inOut.defaultServiceOutMock))\n\
    ```\n\n- Json\n```json\n...\n\"outputServiceMock\": {\n  \"respStatus\" : 200,\n\
    \  \"respBody\" : \"Example String Body\",\n  \"respHeaders\" : [\n  ]\n},\n...\n\
    ```\n\n### Mapping\n**outputVariables**:\n\nYou can filter the Output with a list\
    \ of variable names you are interested in.\nThis list may include all variables\
    \ from the output (`Out`). We included an example for each Process or ExternalTask.\n\
    It is also possible to use a _comma separated_ String,\nlike `\"name,firstName\"\
    `\n\n\n- DSL:\n```scala\nprocess(..) // or serviceTask(..)/customTask(..)\n  .withOutputVariables(\"\
    name\", \"firstName\") // creates a list with outputVariables\n  .withOutputVariable(\"\
    nickname\") // adds a outputVariable\n```\n\n- Json\n```json\n...\n\"outputVariables\"\
    : [\"name\", \"firstName\"],\n...\n```\n\n\n**manualOutMapping**:\n\nBy default\
    \ all output Variables (`Out`) are on the Process for _External Tasks_.\nIf the\
    \ filter _outputVariables_ is not enough,\nyou can set this variable - every output\
    \ variable is then local.\n\n_Be aware_ that you must then manually have _output\
    \ mappings_ for each output variable!\n\n\n- DSL:\n```scala\nserviceTask(..) //\
    \ or customTask(..)\n  .manualOutMapping\n```\n\n- Json\n```json\n...\n\"manualOutMapping\"\
    : true,\n...\n```\n\n### Mocking\n**handledErrors**:\n\nA list of error codes\
    \ that are handled (`BpmnError`)\nIt is also possible to use a _comma separated_\
    \ String,\nlike `\"validation-failed,404\"`\n\nAt the moment only _ServiceTasks_\
    \ supported.\n\n\n- DSL:\n```scala\nserviceTask(..)\n  .handleErrors(ErrorCodes.`validation-failed`,\
    \ \"404\") // create a list of handledErrors\n  .handleError(\"404\") // add a\
    \ handledError\n```\n\n- Json\n```json\n...\n\"handledErrors\": [\"validation-failed\"\
    , \"404\"],\n...\n```\n\n\n**regexHandledErrors**:\n\nYou can further filter Handled\
    \ Errors with a list of Regex expressions that the body error message must match.\n\
    It is also possible to use a _comma separated_ String,\nlike `\"SQL exception,\"\
    errorNr\":\"20000\"\"`\n\nAt the moment only _ServiceTasks_ supported.\n\n\n-\
    \ DSL:\n```scala\nserviceTask(..)\n  .handleErrorWithRegex(\"SQL exception\")\n\
    \  .handleErrorWithRegex(\"\\\"errorNr\\\":\\\"20000\\\"\")\n```\n\n- Json\n```json\n\
    ...\n\"regexHandledErrors\": [\"SQL exception\", \"\"errorNr\":\"20000\"\"],\n\
    ...\n```\n\n### Authorization\n**impersonateUserId**:\n\nUser-ID of a User that\
    \ should be taken to authenticate to the services.\nThis must be supported by\
    \ your implementation. *Be caution: this may be a security issue!*.\nIt is helpful\
    \ if you have Tokens that expire, but long running Processes.\n\n- DSL:\n```scala\n\
    process(..) // or serviceTask(..)/customTask(..)\n  .withImpersonateUserId(impersonateUserId)\n\
    ```\n\n- Json\n```json\n...\n\"impersonateUserId\": \"myUserName\",\n...\n```\n\
    \n</p>\n</details>\n<p/>\n        \n\n> Created with:\n> - [orchescala-api v0.3.0-SNAPSHOT](https://github.com/pme123/orchescala)\n\
    > - democompany-orchescala-api 0.1.0-SNAPSHOT\n> - democompany-orchescala-helper\n\
    \n"
paths:
  /Worker/Clients1.0/clientsV1-GetClientsClientId/democompany-services-clientsV1-GetClientsClientId:
    head:
      tags:
      - Clients 1.0
      summary: 'Worker: GetClientsClientId'
      description: "\n\n\n**Topic:** `democompany-services-clientsV1-GetClientsClientId`\
        \ (to define in the _**Topic**_ of the _**External Task**_ > _Service Task_\
        \ of type _External_)\n\nGet the Client by Id\n\n---\n\n\n\n<details>\n<summary><b>Wrapped\
        \ Service:</b>\n\n(Clients 1.0 - v1.0 - GET: clients/clientId)\n</summary>\n\
        <p>\nInput Body: `orchescala.domain.NoInput`:\n\n\nExample Response: `democompany.services.domain.clients.v1.schema.Client`:\n\
        \n```json\n{\n  \"respStatus\" : 200,\n  \"respBody\" : {\n    \"id\" : 1,\n\
        \    \"firstName\" : \"John\",\n    \"lastName\" : \"Doe\",\n    \"email\"\
        \ : \"john.doe@example.com\",\n    \"address\" : {\n      \"street\" : \"\
        Main Street\",\n      \"number\" : \"123\",\n      \"zip\" : \"12345\",\n\
        \      \"city\" : \"Anytown\",\n      \"country\" : \"Germany\",\n      \"\
        additionalInfo\" : \"Additional Info\"\n    }\n  },\n  \"respHeaders\" : [\n\
        \    [\n      \"ETag\",\n      \"12345.234324234.2343423432\"\n    ]\n  ]\n\
        }\n```\n</p>\n</details>\n</p>\n\n---\n\n\n- Input:  `democompany.services.domain.clients.v1.GetClientsClientId\
        \ > In`\n- Output: `democompany.services.domain.clients.v1.GetClientsClientId\
        \ > Out`\n\nYou can test this worker using the generic process _**orchescala-externalTask-generic**_\
        \ (e.g. with Postman).\n\n- ServiceOut:  `orchescala.domain.MockedServiceResponse`\n\
        <p/>\n\n<details>\n<summary>\n<b><i>General Variable(s)</i></b>\n</summary>\n\
        \n<p>\n\n**outputVariables**:\n\nJust take the variable you need in your process!\n\
        ```json\n...\n\"outputVariables\": \"client,etag\",\n...\n```\n\n**outputMock**:\n\
        \n```json\n...\n\"outputMock\": {\n  \"client\" : {\n    \"id\" : 1,\n   \
        \ \"firstName\" : \"John\",\n    \"lastName\" : \"Doe\",\n    \"email\" :\
        \ \"john.doe@example.com\",\n    \"address\" : {\n      \"street\" : \"Main\
        \ Street\",\n      \"number\" : \"123\",\n      \"zip\" : \"12345\",\n   \
        \   \"city\" : \"Anytown\",\n      \"country\" : \"Germany\",\n      \"additionalInfo\"\
        \ : \"Additional Info\"\n    }\n  },\n  \"etag\" : \"12345.234324234.2343423432\"\
        \n},\n...\n```\n\n**outputServiceMock**:\n```json\n...\n\"outputServiceMock\"\
        : {\n  \"respStatus\" : 200,\n  \"respBody\" : {\n    \"respStatus\" : 200,\n\
        \    \"respBody\" : {\n      \"id\" : 1,\n      \"firstName\" : \"John\",\n\
        \      \"lastName\" : \"Doe\",\n      \"email\" : \"john.doe@example.com\"\
        ,\n      \"address\" : {\n        \"street\" : \"Main Street\",\n        \"\
        number\" : \"123\",\n        \"zip\" : \"12345\",\n        \"city\" : \"Anytown\"\
        ,\n        \"country\" : \"Germany\",\n        \"additionalInfo\" : \"Additional\
        \ Info\"\n      }\n    },\n    \"respHeaders\" : [\n      [\n        \"ETag\"\
        ,\n        \"12345.234324234.2343423432\"\n      ]\n    ]\n  },\n  \"respHeaders\"\
        \ : [\n  ]\n},\n...\n```\n</p>\n</details>\n</p>\n      \n    \n\n\n**Used\
        \ in no other Process.**\n\n**Uses no other Processes.**\n"
      operationId: 'Worker: GetClientsClientId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In'
            examples:
              democompany-services-clientsV1-GetClientsClientId:
                value:
                  clientId: 1234
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out'
              examples:
                democompany-services-clientsV1-GetClientsClientId:
                  value:
                    client:
                      id: 1
                      firstName: John
                      lastName: Doe
                      email: john.doe@example.com
                      address:
                        street: Main Street
                        number: '123'
                        zip: '12345'
                        city: Anytown
                        country: Germany
                        additionalInfo: Additional Info
                    etag: 12345.234324234.2343423432
components:
  schemas:
    Address:
      title: Address
      type: object
      required:
      - street
      - number
      - zip
      - city
      - country
      properties:
        street:
          type: string
        number:
          type: string
        zip:
          type: string
        city:
          type: string
        country:
          type: string
        additionalInfo:
          type: string
    Client:
      title: Client
      type: object
      required:
      - id
      - firstName
      - lastName
      - address
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    In:
      title: In
      type: object
      required:
      - clientId
      properties:
        clientId:
          type: integer
          format: int64
    Out:
      title: Out
      type: object
      required:
      - client
      - etag
      properties:
        client:
          $ref: '#/components/schemas/Client'
        etag:
          type: string
tags:
- name: Clients 1.0
  description: ''
  x-displayName: Clients 1.0
