openapi: 3.1.0
info:
  title: democompany-services
  version: 0.1.0-SNAPSHOT
  summary: "\n         |**This is for Postman - to have example requests. Be aware\
    \ the Output is not provided!**\n         |\n         |\n\nMy services for the\
    \ democompany\n\nCreated at 11.08.2025, 13:07\n\n**See the [Orchescala Documentation](https://pme123.github.io/orchescala/)**\n\
    \n# Package Configuration\n**Check all dependency trees here: [democompany-services](../../dependencies/democompany-services.html)**\n\
    \n### Dependencies:\n\n\n\n\n<details>\n<summary>PROJECT.conf</summary>\n<p>\n\
    \n```\n\n// Project configuration\n\nprojectName: democompany-services\nprojectVersion:\
    \ 0.1.0-SNAPSHOT\nsubProjects: [\n  // subProject1\n  // subProject2\n]\ndependencies:\
    \ [\n  // mastercompany-services\n  // mycompany-commons\n]\n\n```\n\n</p>\n</details>\n\
    \n\nThere is no README.md in the Project.\n\n\n<details>\n<summary><b><i>CHANGELOG.md</i></b></summary>\n\
    <p>\n\n\nAll notable changes to this project will be documented in this file.\n\
    \n* Types of Changes (L3):\n  * Added: new features\n  * Changed: changes in existing\
    \ functionality\n  * Deprecated: soon-to-be-removed features\n  * Removed: now\
    \ removed features\n  * Fixed: any bug fixes\n  * Security: in case of vulnerabilities\n\
    \n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\n\
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n\
    \n\n</p>\n</details>\n\n\n<p/>\n<details>\n<summary>\n<b><i>General Variables</i></b>\n\
    </summary>\n\n<p>\n\n### Mocking\n\n**servicesMocked**:\n\nMock all the _ServiceWorkers_\
    \ in your process with their default Mock:\n\n- DSL:\n```scala\nprocess(..)\n\
    \  .mockServices\n```\n\n- Json\n```json\n...\n\"servicesMocked\": true,\n...\n\
    ```\n\n\n**mockedWorkers**:\n\nMock any Process- and/or ExternalTask-Worker with\
    \ their default Mocks.\nThis is a list of the _Worker topicNames or Process processNames_,\
    \ you want to mock.\nIt is also possible to use a _comma separated_ String,\n\
    like `\"mySubProcess,myOtherSubProcess,myService\"`\n\n_Be aware_: For Sub-Processes,\
    \ this expects an _InitWorker_ where the _topicName_ is equal to the _processName_.\n\
    \n\n- DSL:\n```scala\nprocess(..)\n  .mockedWorkers(\"mySubProcess1\", \"mySubProcess2\"\
    ) // creates a list with SubProcessess\n  .mockedWorker(\"myOtherSubProcess\"\
    ) // adds a SubProcess\n```\n\n- Json\n```json\n...\n\"mockedWorkers\": [\"mySubProcess\"\
    , \"myOtherSubProcess, myService\"],\n...\n```\n\n\n**outputMock**:\n\nMock the\
    \ Process or ExternalTask (`Out`)\n - You find an example in every _Process_ and\
    \ _ExternalTask_.\n\n\n- DSL:\n```scala\nprocess(..) // or serviceTask(..)/customTask(..)\n\
    \  .mockWith(outputMock)\n```\n\n- Json\n```json\n...\n\"outputMock\": {..},\n\
    ...\n```\n\n\n**outputServiceMock**:\n\nMock the Inner-Service (`MockedServiceResponse[ServiceOut]`)\n\
    \ - You find an example in every _ServiceTask_.\n\n\n- DSL:\n```scala\nserviceTask(..)\n\
    \  .mockServiceWith(MockedServiceResponse\n     .success200(inOut.defaultServiceOutMock))\n\
    ```\n\n- Json\n```json\n...\n\"outputServiceMock\": {\n  \"respStatus\" : 200,\n\
    \  \"respBody\" : \"Example String Body\",\n  \"respHeaders\" : [\n  ]\n},\n...\n\
    ```\n\n### Mapping\n**outputVariables**:\n\nYou can filter the Output with a list\
    \ of variable names you are interested in.\nThis list may include all variables\
    \ from the output (`Out`). We included an example for each Process or ExternalTask.\n\
    It is also possible to use a _comma separated_ String,\nlike `\"name,firstName\"\
    `\n\n\n- DSL:\n```scala\nprocess(..) // or serviceTask(..)/customTask(..)\n  .withOutputVariables(\"\
    name\", \"firstName\") // creates a list with outputVariables\n  .withOutputVariable(\"\
    nickname\") // adds a outputVariable\n```\n\n- Json\n```json\n...\n\"outputVariables\"\
    : [\"name\", \"firstName\"],\n...\n```\n\n\n**manualOutMapping**:\n\nBy default\
    \ all output Variables (`Out`) are on the Process for _External Tasks_.\nIf the\
    \ filter _outputVariables_ is not enough,\nyou can set this variable - every output\
    \ variable is then local.\n\n_Be aware_ that you must then manually have _output\
    \ mappings_ for each output variable!\n\n\n- DSL:\n```scala\nserviceTask(..) //\
    \ or customTask(..)\n  .manualOutMapping\n```\n\n- Json\n```json\n...\n\"manualOutMapping\"\
    : true,\n...\n```\n\n### Mocking\n**handledErrors**:\n\nA list of error codes\
    \ that are handled (`BpmnError`)\nIt is also possible to use a _comma separated_\
    \ String,\nlike `\"validation-failed,404\"`\n\nAt the moment only _ServiceTasks_\
    \ supported.\n\n\n- DSL:\n```scala\nserviceTask(..)\n  .handleErrors(ErrorCodes.`validation-failed`,\
    \ \"404\") // create a list of handledErrors\n  .handleError(\"404\") // add a\
    \ handledError\n```\n\n- Json\n```json\n...\n\"handledErrors\": [\"validation-failed\"\
    , \"404\"],\n...\n```\n\n\n**regexHandledErrors**:\n\nYou can further filter Handled\
    \ Errors with a list of Regex expressions that the body error message must match.\n\
    It is also possible to use a _comma separated_ String,\nlike `\"SQL exception,\"\
    errorNr\":\"20000\"\"`\n\nAt the moment only _ServiceTasks_ supported.\n\n\n-\
    \ DSL:\n```scala\nserviceTask(..)\n  .handleErrorWithRegex(\"SQL exception\")\n\
    \  .handleErrorWithRegex(\"\\\"errorNr\\\":\\\"20000\\\"\")\n```\n\n- Json\n```json\n\
    ...\n\"regexHandledErrors\": [\"SQL exception\", \"\"errorNr\":\"20000\"\"],\n\
    ...\n```\n\n### Authorization\n**impersonateUserId**:\n\nUser-ID of a User that\
    \ should be taken to authenticate to the services.\nThis must be supported by\
    \ your implementation. *Be caution: this may be a security issue!*.\nIt is helpful\
    \ if you have Tokens that expire, but long running Processes.\n\n- DSL:\n```scala\n\
    process(..) // or serviceTask(..)/customTask(..)\n  .withImpersonateUserId(impersonateUserId)\n\
    ```\n\n- Json\n```json\n...\n\"impersonateUserId\": \"myUserName\",\n...\n```\n\
    \n</p>\n</details>\n<p/>\n        \n\n> Created with:\n> - [orchescala-api v0.3.0-SNAPSHOT](https://github.com/pme123/orchescala)\n\
    > - democompany-orchescala-api 0.1.0-SNAPSHOT\n> - democompany-orchescala-helper\n\
    \n\n         |"
servers:
- url: http://localhost:8080/engine-rest
  description: Local Developer Server
paths:
  /process-definition/key/orchescala-externalTask-generic/start--REMOVE:democompany-services-clientsV1-GetClientsClientId--:
    post:
      tags:
      - Clients 1.0
      summary: 'Worker: GetClientsClientId'
      description: |
        Get the Client by Id

        ---



        <details>
        <summary><b>Wrapped Service:</b>

        (Clients 1.0 - v1.0 - GET: clients/clientId)
        </summary>
        <p>
        Input Body: `orchescala.domain.NoInput`:


        Example Response: `democompany.services.domain.clients.v1.schema.Client`:

        ```json
        {
          "respStatus" : 200,
          "respBody" : {
            "id" : 1,
            "firstName" : "John",
            "lastName" : "Doe",
            "email" : "john.doe@example.com",
            "address" : {
              "street" : "Main Street",
              "number" : "123",
              "zip" : "12345",
              "city" : "Anytown",
              "country" : "Germany",
              "additionalInfo" : "Additional Info"
            }
          },
          "respHeaders" : [
            [
              "ETag",
              "12345.234324234.2343423432"
            ]
          ]
        }
        ```
        </p>
        </details>
        </p>

        ---


        See API Doc: [Worker: GetClientsClientId](None/democompany-services/OpenApi.html#operation/Worker:%20GetClientsClientId)
      operationId: postProcess-definitionKeyOrchescala-externaltask-genericStart--remove:democompany-services-clientsv1-getclientsclientid--
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartProcessIn'
            examples:
              democompany-services-clientsV1-GetClientsClientId:
                value:
                  variables:
                    clientId:
                      value: 1234
                      type: Long
                  businessKey: democompany-services-clientsV1-GetClientsClientId
                  withVariablesInReturn: true
        required: true
      responses:
        '200':
          description: ''
  /process-definition/key/orchescala-externalTask-generic/start--REMOVE:democompany-services-mailsV1-SendEmail--:
    post:
      tags:
      - Mails 1.0
      summary: 'Worker: SendEmail'
      description: "Send an Email\n\n---\n\n\n\n<details>\n<summary><b>Wrapped Service:</b>\n\
        \n(Mails 1.0 - v1.0 - PUT: mail)\n</summary>\n<p>\nInput Body: `democompany.services.domain.mails.v1.SendEmail$In`:\n\
        \n```json\n{\n  \"subject\" : \"Request for Information\",\n  \"body\" : \"\
        Dear John, how are you?</br>We need more information.</br> - Passport or Drivers\
        \ License</br> - Proof of Address</br>Kind regards, Jane\",\n  \"to\" : \"\
        john.doe@example.com\",\n  \"cc\" : \"jane.doe@example.com\"\n}\n```\n\n\n\
        Example Response: `orchescala.domain.NoOutput`:\n\n```json\n{\n  \"respStatus\"\
        \ : 204,\n  \"respBody\" : {\n    \n  },\n  \"respHeaders\" : [\n  ]\n}\n\
        ```\n</p>\n</details>\n</p>\n\n---\n\n\nSee API Doc: [Worker: SendEmail](None/democompany-services/OpenApi.html#operation/Worker:%20SendEmail)\n"
      operationId: postProcess-definitionKeyOrchescala-externaltask-genericStart--remove:democompany-services-mailsv1-sendemail--
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartProcessIn'
            examples:
              democompany-services-mailsV1-SendEmail:
                value:
                  variables:
                    body:
                      value: |-
                        Dear John, how are you?
                        We need more information.
                         - Passport or Drivers License
                         - Proof of Address
                        Kind regards, Jane
                      type: String
                    subject:
                      value: Request for Information
                      type: String
                    to:
                      value: john.doe@example.com
                      type: String
                    cc:
                      value: jane.doe@example.com
                      type: String
                  businessKey: democompany-services-mailsV1-SendEmail
                  withVariablesInReturn: true
        required: true
      responses:
        '200':
          description: ''
components:
  schemas:
    CBoolean:
      title: CBoolean
      type: object
      required:
      - value
      - type
      properties:
        value:
          type: boolean
        type:
          type: string
    CDouble:
      title: CDouble
      type: object
      required:
      - value
      - type
      properties:
        value:
          type: number
          format: double
        type:
          type: string
    CFile:
      title: CFile
      type: object
      required:
      - value
      - valueInfo
      - type
      properties:
        value:
          description: The File's content as Base64 encoded String.
          type: string
        valueInfo:
          $ref: '#/components/schemas/CFileValueInfo'
        type:
          type: string
    CFileValueInfo:
      title: CFileValueInfo
      type: object
      required:
      - filename
      properties:
        filename:
          type: string
        mimetype:
          type: string
    CInteger:
      title: CInteger
      type: object
      required:
      - value
      - type
      properties:
        value:
          type: integer
          format: int32
        type:
          type: string
    CJson:
      title: CJson
      type: object
      required:
      - value
      - type
      properties:
        value:
          type: string
        type:
          type: string
    CLong:
      title: CLong
      type: object
      required:
      - value
      - type
      properties:
        value:
          type: integer
          format: int64
        type:
          type: string
    CNull:
      title: CNull
      type: object
    CString:
      title: CString
      type: object
      required:
      - value
      - type
      properties:
        value:
          type: string
        type:
          type: string
    CamundaVariable:
      title: CamundaVariable
      oneOf:
      - $ref: '#/components/schemas/CBoolean'
      - $ref: '#/components/schemas/CDouble'
      - $ref: '#/components/schemas/CFile'
      - $ref: '#/components/schemas/CInteger'
      - $ref: '#/components/schemas/CJson'
      - $ref: '#/components/schemas/CLong'
      - $ref: '#/components/schemas/CNull'
      - $ref: '#/components/schemas/CString'
    Map_CamundaVariable:
      title: Map_CamundaVariable
      type: object
      additionalProperties:
        $ref: '#/components/schemas/CamundaVariable'
    StartProcessIn:
      title: StartProcessIn
      description: 'A JSON object with the following properties: (at least an empty
        JSON object {} or an empty request body)'
      type: object
      required:
      - variables
      - withVariablesInReturn
      properties:
        variables:
          $ref: '#/components/schemas/Map_CamundaVariable'
        businessKey:
          description: The business key of the process instance.
          type: string
        withVariablesInReturn:
          description: Set to false will not return the Process Variables.
          type: boolean
